CREATE DATABASE AERONAVES;

USE AERONAVES;

CREATE TABLE POSTO(
ID_POSTO INT auto_increment NOT NULL PRIMARY KEY,
DESCRICAO_POSTO VARCHAR(45) NOT NULL,
FLAG_PILOTO INT NOT NULL
);

CREATE TABLE MISSAO(
ID_MISSAO INT auto_increment NOT NULL PRIMARY KEY,
CODINOME VARCHAR(10) NOT NULL,
DESCRITIVO_MISSAO VARCHAR(300) NOT NULL
);

CREATE TABLE STATUS(
ID_STATUS INT auto_increment NOT NULL PRIMARY KEY,
DESCRICAO_STATUS VARCHAR(45) NOT NULL
);

CREATE TABLE FUNCAO(
ID_FUNCAO INT auto_increment NOT NULL PRIMARY KEY,
DESCRICAO_FUNCAO VARCHAR(45) NOT NULL
);

CREATE TABLE TIPO_AERONAVE(
ID_TIPO_AERONAVE INT auto_increment NOT NULL PRIMARY KEY,
DESCRICAO_TIPO_AERONAVE VARCHAR(45) NOT NULL
);

CREATE TABLE TRIPULACAO(
REGISTRO INT auto_increment NOT NULL PRIMARY KEY,
ID_POSTO INT NOT NULL,
NOME_TRIPULANTE VARCHAR(45) NOT NULL,
NOMKE_GUERRA VARCHAR(45) NOT NULL,
TIPO_SANGUINEO VARCHAR(2) NOT NULL,
RH_SANGUE VARCHAR(8) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
DATA_ENTRADA_ATIVA DATE NOT NULL,
DDD_TELEFONE_FIXO INT NOT NULL,
NUMERO_TELEFONE_FIXO BIGINT NOT NULL,
DDD_TELEFONE_CELULAR INT NOT NULL,
NUMERO_TELEFONE_CELULAR BIGINT NOT NULL,
CONSTRAINT FK_TRIPULACAO_POSTO FOREIGN KEY (ID_POSTO) REFERENCES POSTO(ID_POSTO)
);

CREATE TABLE AERONAVE(
PREFIXO VARCHAR(5) NOT NULL PRIMARY KEY,
ID_STATUS INT NOT NULL,
ID_TIPO_AERONAVE INT NOT NULL,
APELIDO VARCHAR(10) NOT NULL,
COR VARCHAR(20) NOT NULL,
DATA_FABRICACAO DATE NOT NULL,
NR_TRIPULANTES INT NOT NULL,
CONSTRAINT FK_AERONAVE_STATUS FOREIGN KEY (ID_STATUS) REFERENCES STATUS(ID_STATUS),
CONSTRAINT FK_AERONAVE_TIPO_AERONAVE FOREIGN KEY (ID_TIPO_AERONAVE) REFERENCES TIPO_AERONAVE(ID_TIPO_AERONAVE)
);

CREATE TABLE ESCALA(
REGISTRO INT NOT NULL PRIMARY KEY,
DATA_ESCALA DATE NOT NULL,
PREFIXO VARCHAR(5) NOT NULL,
ID_MISSAO INT NOT NULL,
ID_FUNCAO INT NOT NULL,
CONSTRAINT FK_ESCALA_PREFIXO FOREIGN KEY (PREFIXO) REFERENCES AERONAVE(PREFIXO),
CONSTRAINT FK_ESCALA_MISSAO FOREIGN KEY (ID_MISSAO) REFERENCES MISSAO(ID_MISSAO),
CONSTRAINT FK_ESCALA_FUNCAO FOREIGN KEY (ID_FUNCAO) REFERENCES FUNCAO(ID_FUNCAO)
);

ALTER TABLE MISSAO MODIFY DESCRITIVO_MISSAO VARCHAR(100);
ALTER TABLE FUNCAO ADD STATUS VARCHAR(20);
